events {}

http {
    upstream backend {
        # docker-compose.yml 안의 서비스 이름 `app` 기준
        server memory-app:8081;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}
