# =========================
# 기본 (local / default)
# =========================
spring:
  config:
    import: optional:application-secret.yml

  datasource:
    url: jdbc:mysql://localhost:3306/memory_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: memory_user
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        timezone:
          default_storage: NORMALIZE_UTC
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8081
  forward-headers-strategy: none
  ssl:
    enabled: false
  use-forward-headers: false
  tomcat:
    max-http-post-size: 524288000  # 500MB in bytes
    max-http-header-size: 102400   # 100KB in byt
  #max-http-request-size: 500MB     # 기존 server.tomcat.max-http-post-size 대체

memory:
  base-url: https://me-mory01.mooo.com
  file-upload:
    max-file-size: 524288000
    allowed-image-types:
      - image/jpeg
      - image/jpg
      - image/png
      - image/gif
      - image/webp
      - image/heic
    allowed-image-extensions:
      - ".jpg"
      - ".jpeg"
      - ".png"
      - ".gif"
      - ".webp"
      - ".heic"

kakao:
  client-id: ${KAKAO_CLIENT_ID}  # application-secret.yml에서 주입
  redirect-uri: http://localhost:8081/api/auth/login/kakao

