server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=DEBUG
logging.level.zim.tave.memory=DEBUG
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=https://me-mory01.mooo.com/v3/api-docs
